"""
Re-score conversations already generated by generate_example_convo.py (or another script
producing the same shape) against every persona-vector activation-extraction method
(ACTIVATION_TYPES), for comparison. Does NOT generate any new conversation turns -- it only
reads --input (an example_convos.json-shaped file: {label: {assistant_system_prompt, turns:
[{turn, mode, user, assistant}, ...]}}) and replaces each turn's scoring with
persona_scores_by_activation_type, consumed by graph_convo.py.

Errors if --input does not exist -- run generate_example_convo.py first to produce it.
"""
import argparse
import json
import logging
import os
import warnings
from pathlib import Path

import torch
from dotenv import load_dotenv
from huggingface_hub import login
from huggingface_hub.utils import logging as hf_logging
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import logging as transformers_logging

MODEL_NAME = "meta-llama/Llama-3.1-8B-Instruct"
VECTORS_DIR = Path(__file__).parent / "../generation/persona_vectors"

# Four ways to extract a persona-vector-scoring activation from one forward pass over the
# full conversation so far: response_final/user_final (last token of the response/prompt),
# conversation_mean (mean over the whole conversation so far), response_mean (mean over just
# this turn's response tokens).
ACTIVATION_TYPES = ("response_final", "user_final", "conversation_mean", "response_mean")

# "No context" counterparts, computed from a second forward pass over just this turn's
# exchange in isolation (empty prior_history) instead of the full conversation -- lets you
# compare whether the signal depends on conversation-so-far or is inherent to one exchange.
# conversation_mean has no counterpart here (it would just equal this isolated exchange).
NO_CONTEXT_BASE_TYPES = ("response_final", "user_final", "response_mean")
NO_CONTEXT_ACTIVATION_TYPES = tuple(f"{t}_no_context" for t in NO_CONTEXT_BASE_TYPES)
ALL_ACTIVATION_TYPES = ACTIVATION_TYPES + NO_CONTEXT_ACTIVATION_TYPES

# Currently disabled -- flip to True to also compute/score NO_CONTEXT_ACTIVATION_TYPES.
COMPUTE_NO_CONTEXT = False


def parse_args():
    parser = argparse.ArgumentParser(
        description="Re-score an existing example_convos.json-shaped file's conversations "
                    "across every activation-extraction method. Does not generate new turns."
    )
    parser.add_argument("--input", type=str, default=str(Path(__file__).parent / "example_convos.json"),
                         help="Path to the conversations JSON to re-score (as produced by "
                              "generate_example_convo.py)")
    parser.add_argument("--scenarios", type=str, nargs="+", default=["all"],
                         help="Which conversation labels (top-level keys of --input) to "
                              "re-score, or 'all' for every one. Defaults to all.")
    parser.add_argument("--output-dir", type=str, default=".", help="Directory to write output JSON files to")
    return parser.parse_args()


def _template_length(tokenizer, messages, add_generation_prompt):
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=add_generation_prompt)
    return tokenizer(text, return_tensors="pt").input_ids.shape[1]


def get_turn_activations(model, tokenizer, system_prompt, prior_history, user_msg, assistant_msg, layer_idxs, device):
    """All four ACTIVATION_TYPES, for each layer in `layer_idxs`, from one forward pass over
    the full conversation (system prompt + prior_history + this turn's user_msg + assistant_msg).

    prior_history is the accumulated conversation from BEFORE this turn (i.e. not yet
    including the user_msg/assistant_msg being scored), so the boundary between "this turn's
    user message" and "this turn's response" can be located by template-rendering length
    rather than by string slicing.
    """
    system_message = {"role": "system", "content": system_prompt}
    prior_messages = [system_message] + prior_history
    with_user_messages = prior_messages + [{"role": "user", "content": user_msg}]
    full_messages = with_user_messages + [{"role": "assistant", "content": assistant_msg}]

    response_start_len = _template_length(tokenizer, with_user_messages, add_generation_prompt=True)

    full_prompt = tokenizer.apply_chat_template(full_messages, tokenize=False, add_generation_prompt=False)
    inputs = tokenizer(full_prompt, return_tensors="pt").to(device)
    full_len = inputs["input_ids"].shape[1]

    captured = {}

    def make_hook(layer_idx):
        def hook_fn(_module, _args, output):
            captured[layer_idx] = output[0].detach().to(torch.bfloat16)  # (seq_len, d_model)
        return hook_fn

    hooks = [
        model.model.layers[layer_idx].register_forward_hook(make_hook(layer_idx))
        for layer_idx in layer_idxs
    ]
    try:
        with torch.no_grad():
            model(**inputs)
    finally:
        for hook in hooks:
            hook.remove()

    activations = {activation_type: {} for activation_type in ACTIVATION_TYPES}
    for layer_idx in layer_idxs:
        seq = captured[layer_idx]
        activations["response_final"][layer_idx] = seq[full_len - 1, :]
        activations["user_final"][layer_idx] = seq[response_start_len - 1, :]
        activations["conversation_mean"][layer_idx] = seq[:full_len, :].mean(dim=0)
        activations["response_mean"][layer_idx] = seq[response_start_len:full_len, :].mean(dim=0)

    return activations


def cosine_similarity(a, b):
    return torch.dot(a, b) / (torch.norm(a) * torch.norm(b))


def compute_persona_scores(activations, traits, scale, persona_vectors, device):
    """activations: {layer_idx: vector} for a single activation type (see get_turn_activations).

    Scores are raw cosine similarity between the activation and the trait's persona vector --
    unscaled, i.e. not rescaled against scale.json's per-trait midpoint/min/max (unlike the
    calibration modal/persona_score_api.py applies at runtime). `scale` is only consulted for
    each trait's layer_idx (which layer's activation/vector to compare).
    """
    persona_scores = {}
    for trait, labels in traits.items():
        layer_idx = scale[trait]["layer_idx"]

        vector = persona_vectors[trait][layer_idx].to(device)
        activation = activations[layer_idx].to(device)

        score = cosine_similarity(activation.flatten(), vector.flatten()).item()

        positive, negative = (score, 0.0) if score > 0 else (0.0, -score)
        persona_scores[trait] = {
            labels["positive"]: positive,
            labels["negative"]: negative,
        }

    return persona_scores


def rescore_conversation(
    model, tokenizer, convo, traits, scale, persona_vectors, device, label, pbar,
    results, output_path,
):
    assistant_system_prompt = convo["assistant_system_prompt"]
    source_turns = convo["turns"]
    turns_log = []
    needed_layers = {stats["layer_idx"] for stats in scale.values()}
    results[label] = {
        "user_scenario": convo["user_scenario"],
        "assistant_system_prompt": assistant_system_prompt,
        "turns": turns_log,
        "activation_types": list(ALL_ACTIVATION_TYPES if COMPUTE_NO_CONTEXT else ACTIVATION_TYPES),
    }

    prior_history = []  # accumulated conversation from BEFORE the turn currently being scored
    for source_turn in source_turns:
        pbar.set_description(f"{label} | turn {source_turn['turn']}/{len(source_turns)}")

        user_msg, assistant_msg = source_turn["user"], source_turn["assistant"]

        activations_by_type = get_turn_activations(
            model, tokenizer, assistant_system_prompt, prior_history, user_msg, assistant_msg,
            needed_layers, device,
        )

        if COMPUTE_NO_CONTEXT:
            no_context_activations = get_turn_activations(
                model, tokenizer, assistant_system_prompt, [], user_msg, assistant_msg,
                needed_layers, device,
            )
            for base_type in NO_CONTEXT_BASE_TYPES:
                activations_by_type[f"{base_type}_no_context"] = no_context_activations[base_type]

        turn_entry = {
            "turn": source_turn["turn"],
            "mode": source_turn["mode"],
            "user": user_msg,
            "assistant": assistant_msg,
            "persona_scores_by_activation_type": {
                activation_type: compute_persona_scores(activations, traits, scale, persona_vectors, device)
                for activation_type, activations in activations_by_type.items()
            },
        }

        turns_log.append(turn_entry)
        prior_history = prior_history + [
            {"role": "user", "content": user_msg},
            {"role": "assistant", "content": assistant_msg},
        ]

        with open(output_path, "w") as f:
            json.dump(results, f, indent=2, ensure_ascii=False)

        pbar.update(1)

    return turns_log


def _silence_non_tqdm_output():
    warnings.filterwarnings("ignore")
    logging.disable(logging.CRITICAL)
    transformers_logging.set_verbosity_error()
    hf_logging.set_verbosity_error()
    os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
    os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")


def main():
    _silence_non_tqdm_output()
    load_dotenv()
    login(token=os.environ.get("HF_TOKEN"))
    args = parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(
            f"{input_path} does not exist. Generate it first, e.g. with generate_example_convo.py."
        )
    with open(input_path) as f:
        source_conversations = json.load(f)

    scenario_labels = list(source_conversations.keys()) if "all" in args.scenarios else args.scenarios
    missing = [label for label in scenario_labels if label not in source_conversations]
    if missing:
        raise ValueError(f"Labels not found in {input_path}: {', '.join(missing)}")
    scenarios_to_run = {label: source_conversations[label] for label in scenario_labels}

    with open(VECTORS_DIR / "traits.json") as f:
        traits = json.load(f)
    with open(VECTORS_DIR / "scale.json") as f:
        scale = json.load(f)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, dtype=torch.bfloat16).to(device)
    model.eval()

    persona_vectors = {
        trait: torch.load(VECTORS_DIR / f"{trait}.pt", weights_only=False).to(torch.bfloat16)
        for trait in traits
    }

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_path = output_dir / "example_convos_comparison.json"
    # Load any existing results so re-scoring just a subset of scenarios (e.g.
    # --scenarios prompt_1) merges into the file instead of dropping the other scenarios'
    # previously-scored data. Labels being re-scored this run are overwritten below by
    # rescore_conversation; labels not in scenarios_to_run are left untouched.
    results = {}
    if output_path.exists():
        with open(output_path) as f:
            results = json.load(f)

    total_turns = sum(len(convo["turns"]) for convo in scenarios_to_run.values())
    with tqdm(total=total_turns, unit="turn") as pbar:
        for label, convo in scenarios_to_run.items():
            rescore_conversation(
                model, tokenizer, convo, traits, scale, persona_vectors, device, label, pbar,
                results, output_path,
            )


if __name__ == "__main__":
    main()
